"""產生 nas/internal/pystr/casefold_table.go：Python str.casefold() 和 str.lower() 不同的字元。

    .venv-linux/bin/python tools/gen_casefold.py

Go 沒有 Python 的完整 case folding（例如 İ → i̇、ß → ss），pystr.Casefold 查這張表，其餘用 unicode.ToLower。
"""
from pathlib import Path
import subprocess
import sys

OUT = Path(__file__).resolve().parents[1] / "nas" / "internal" / "pystr" / "casefold_table.go"


def go_string(s: str) -> str:
    return '"' + "".join(f"\\u{ord(c):04x}" if ord(c) <= 0xFFFF else f"\\U{ord(c):08x}" for c in s) + '"'


def main() -> None:
    rows = []
    for code in range(0x110000):
        if 0xD800 <= code <= 0xDFFF:
            continue
        ch = chr(code)
        folded = ch.casefold()
        if len(folded) > 1 or folded != ch.lower():
            rows.append(f"\t0x{code:x}: {go_string(folded)},")
    OUT.write_text(
        f"// Code generated by tools/gen_casefold.py（Python {sys.version.split()[0]}）. DO NOT EDIT.\n\n"
        "package pystr\n\n"
        "// casefoldSpecial 是 Python str.casefold() 結果和 str.lower() 不同的字元。\n"
        "var casefoldSpecial = map[rune]string{\n" + "\n".join(rows) + "\n}\n",
        encoding="utf-8")
    subprocess.run(["gofmt", "-w", str(OUT)], check=True)
    print(f"{OUT}：{len(rows)} 個字元")


if __name__ == "__main__":
    main()
