/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 匯出
         * @description 把「已確認」的伴唱帶依曲庫結構同步到匯出資料夾（檔名「歌手 - 歌名.mp4」；設定打開時加上原曲音訊「歌手 - 歌名_original.m4a」）。只在呼叫時執行，不會自動匯出；取消確認、改名或換資料夾的歌，舊的匯出檔會在這時移除。
         */
        post: operations["export"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/folders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 所有資料夾 */
        get: operations["list-folders"];
        put?: never;
        /** 新增資料夾 */
        post: operations["add-folder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/folders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * 刪除資料夾
         * @description 裡面的子資料夾與歌移到上一層，不刪任何檔案。
         */
        delete: operations["delete-folder"];
        options?: never;
        head?: never;
        /** 改名、改順序或移動資料夾 */
        patch: operations["update-folder"];
        trace?: never;
    };
    "/api/v1/fonts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 字型
         * @description fonts/ 裡的字型（含 .ttc 裡的每一個）。字型檔本身在 GET /fonts/{sha256}。
         */
        get: operations["list-fonts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 所有工作
         * @description 新的在前；結束的工作保留最近 200 件、7 天。
         */
        get: operations["list-jobs"];
        put?: never;
        /**
         * 建立工作
         * @description 每首歌一件工作。only_needed 時略過不需要做的歌（已完成、缺歌詞、處理中），回傳略過的原因與首數。
         */
        post: operations["submit-jobs"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 一件工作 */
        get: operations["get-job"];
        put?: never;
        post?: never;
        /**
         * 取消工作
         * @description 排隊中的直接取消；處理中的在下一個安全點停下（AI 正在對時的話，NAS 不等它做完）。
         */
        delete: operations["cancel-job"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{id}/log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 工作的紀錄
         * @description 即時更新請用 SSE 的 job.log 事件。
         */
        get: operations["get-job-log"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/library": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 整個曲庫
         * @description 前端初次載入：資料夾、所有歌的摘要（含各階段狀態、疑慮數、目前的工作）、設定、AI 伺服器、工作。
         */
        get: operations["get-library"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/library/place": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 拖曳：移動與排序
         * @description 把歌或資料夾放進某個資料夾、排在某個項目前面。只做最少的編號調整（留的空號不動）。
         */
        post: operations["place"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/lyrics/convert": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 歌詞文字 ↔ 結構互轉
         * @description 只給 doc：從結構產生各種檢視；給 text：依 format 解析（plain 要一起給原本的 doc 才能保留演唱者與讀音）。標註原文需要自動讀音才能判斷哪些是手動的：AI 不在線時回 409。
         */
        post: operations["convert-lyrics"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 全域設定 */
        get: operations["get-settings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 修改全域設定
         * @description 字幕大小、每種語言的字型。改了之後做好的伴唱帶顯示需更新（只重燒）。
         */
        patch: operations["update-settings"];
        trace?: never;
    };
    "/api/v1/songs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 所有歌的摘要 */
        get: operations["list-songs"];
        put?: never;
        /**
         * 新增歌曲（貼網址）
         * @description 建立下載工作，回 202；Location 指向工作。make=true 時一路做到伴唱帶（有歌詞才製作）。
         */
        post: operations["add-song"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/songs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 一首歌的摘要 */
        get: operations["get-song"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 修改歌曲資訊
         * @description 只改有給的欄位。歌名、演唱者給空字串 = 回到自動辨識；語言給空字串 = 依歌詞判斷。
         */
        patch: operations["update-song"];
        trace?: never;
    };
    "/api/v1/songs/{id}/approval": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * 已確認 / 取消確認
         * @description 只能確認已經做好、而且是最新的伴唱帶。之後對時、歌詞、演唱者、翻譯或標題畫面改了會變成需重新確認（換字型、改字幕大小不影響）。
         */
        put: operations["set-approval"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/songs/{id}/lines/{n}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 改一句的文字或演唱者
         * @description 立刻存檔。改了文字之後，製作伴唱帶時只重對這一句（手動調過的保留開頭）。
         */
        patch: operations["edit-line"];
        trace?: never;
    };
    "/api/v1/songs/{id}/lyrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 歌詞的各種檢視
         * @description 結構（含假名片段）、存檔格式、標註原文、原始歌詞。日文的自動假名由 AI 伺服器算；還沒算好的句子列在 pending_readings，算好後送 readings 事件。
         */
        get: operations["get-lyrics"];
        /**
         * 儲存歌詞
         * @description 改了歌詞文字或讀音：製作伴唱帶時只重對改過的句子，其他句子的時間（含手動調整）不動；人聲、語言或對時方法也改了時才整首重新對時。
         */
        put: operations["put-lyrics"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/songs/{id}/qa": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 對時檢查結果
         * @description 只列有疑慮的句子；對時改過之後 checked 為 false。
         */
        get: operations["get-qa"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/songs/{id}/timing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 每句目前的時間
         * @description 還沒對時時 lines 為空。
         */
        get: operations["get-timing"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/songs/{id}/timing/lines/{n}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 移動一句
         * @description 只移這一句：往後撞到下一句時把它往後推、往前撞到上一句時把它往前推（連鎖），唱不完的部分壓縮。回傳的 pushed 是一起被推動的句子。之後伴唱帶顯示需更新（只重燒，不重新對時）。
         */
        patch: operations["shift-line"];
        trace?: never;
    };
    "/api/v1/system": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 系統資訊
         * @description 版本、yt-dlp、磁碟用量。
         */
        get: operations["get-system"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/ytdlp/rollback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * yt-dlp 退回上一版
         * @description 自動更新後下載失敗時用；再按一次可以換回新版。
         */
        post: operations["rollback-ytdlp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * AI 伺服器
         * @description 名稱、GPU、版本是否相符、目前的任務、最後連線時間。
         */
        get: operations["list-workers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workers/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 停用 / 啟用 AI 伺服器
         * @description 停用的領不到新任務，手上的任務照常做完。
         */
        patch: operations["update-worker"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AddRequest: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/v1/schemas/AddRequest.json
             */
            readonly $schema?: string;
            /** @description 只要音訊 */
            audio_only?: boolean;
            /** @description 放進哪個資料夾（空字串 = 最上層） */
            folder?: string;
            /** @description 一起附上的歌詞（選填） */
            lyrics?: string;
            /** @description 一路做到伴唱帶（下載 → 去人聲 → 有歌詞就製作伴唱帶）；false = 僅下載 */
            make?: boolean;
            /** @description 影片網址 */
            url: string;
        };
        Adjustment: {
            /** Format: double */
            anchor?: number;
            at: string;
            /** Format: double */
            delta?: number;
            following?: boolean;
            /** Format: int64 */
            line: number;
            pushed?: number[];
            retime?: string;
            text: string;
        };
        AlignPatch: {
            /**
             * Format: int64
             * @description 要重對的句子數
             */
            realign: number;
            /**
             * Format: int64
             * @description 拿掉的句子數
             */
            removed: number;
        };
        Approval: {
            at: string;
            fingerprint: string;
            texts?: string[];
        };
        ApprovalInBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/v1/schemas/ApprovalInBody.json
             */
            readonly $schema?: string;
            /** @description true = 標記已確認；false = 取消確認 */
            approved: boolean;
        };
        ApprovalView: {
            /** @description 最近一次確認的時間（stale 時是失效前那次） */
            at?: string;
            /** @description stale 時：和上次確認時相比，歌詞不同的句子（從 0 起算）；沒改歌詞（例如重新去人聲）時為空陣列 */
            changed?: number[];
            /**
             * Format: int64
             * @description 總共確認過幾次
             */
            count: number;
            /**
             * @description approved = 已確認；stale = 曾經確認過，但之後重新對時了；空字串 = 沒確認過
             * @enum {string}
             */
            status: "approved" | "stale" | "";
        };
        ConvertRequest: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/v1/schemas/ConvertRequest.json
             */
            readonly $schema?: string;
            /** @description 結構；format=plain 時是原本的結構（保留演唱者與讀音） */
            doc?: components["schemas"]["Document"];
            /**
             * @description text 的格式：file（存檔格式）、annotated（標註原文）、plain（原始歌詞）
             * @enum {string}
             */
            format?: "file" | "annotated" | "plain";
            /** @description 演唱語言；空字串 = 依歌詞文字判斷 */
            language?: string;
            /** @description 把「運命(さだめ)」這種括號讀音轉成讀音標註（只處理 format=file） */
            paren_to_ruby?: boolean;
            /** @description 這段歌詞是哪首歌的（假名算好時通知用） */
            song?: string;
            /** @description 要轉換的文字；不給時從 doc 產生 */
            text?: string;
        };
        Disk: {
            /** Format: int64 */
            free: number;
            /** Format: int64 */
            total: number;
        };
        Document: {
            lines: components["schemas"]["Line"][];
            meta: {
                [key: string]: string;
            };
        };
        EditorDoc: {
            language: string | null;
            lines: components["schemas"]["EditorLine"][];
            meta: {
                [key: string]: string;
            };
        };
        EditorLine: {
            kind: string;
            rubies: components["schemas"]["Ruby"][];
            segments?: components["schemas"]["Segment"][];
            singer: string | null;
            text: string;
            translation: string;
        };
        ErrorDetail: {
            /** @description Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id' */
            location?: string;
            /** @description Error message text */
            message?: string;
            /** @description The value at the given location */
            value?: unknown;
        };
        ErrorModel: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/v1/schemas/ErrorModel.json
             */
            readonly $schema?: string;
            /**
             * @description A human-readable explanation specific to this occurrence of the problem.
             * @example Property foo is required but is missing.
             */
            detail?: string;
            /** @description Optional list of individual error details */
            errors?: components["schemas"]["ErrorDetail"][];
            /**
             * Format: uri
             * @description A URI reference that identifies the specific occurrence of the problem.
             * @example https://example.com/error-log/abc123
             */
            instance?: string;
            /**
             * Format: int64
             * @description HTTP status code
             * @example 400
             */
            status?: number;
            /**
             * @description A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
             * @example Bad Request
             */
            title?: string;
            /**
             * Format: uri
             * @description A URI reference to human-readable documentation for the error.
             * @default about:blank
             * @example https://example.com/errors/example
             */
            type: string;
        };
        FolderInBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/v1/schemas/FolderInBody.json
             */
            readonly $schema?: string;
            /** @description 名稱；空的話叫「新資料夾」 */
            name?: string;
            /**
             * Format: int64
             * @description 順序；0 = 排到最後
             */
            order?: number;
            /** @description 上一層資料夾 id；空字串 = 最上層 */
            parent?: string;
        };
        FolderPatchBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/v1/schemas/FolderPatchBody.json
             */
            readonly $schema?: string;
            /** @description 新名稱 */
            name?: string;
            /**
             * Format: int64
             * @description 新順序（正整數）
             */
            order?: number;
            /** @description 移到哪個資料夾底下；空字串 = 最上層 */
            parent?: string;
        };
        FolderView: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/v1/schemas/FolderView.json
             */
            readonly $schema?: string;
            id: string;
            name: string;
            /** Format: int64 */
            order: number;
            /** @description 上一層資料夾 id；最上層為空字串 */
            parent: string;
        };
        Font: {
            default: boolean;
            family: string;
            file: string;
            full_name: string;
            id: string;
            /** Format: int64 */
            index: number;
            /** Format: double */
            scale: number;
            sha256: string;
            /** Format: int64 */
            weight: number;
        };
        FontView: {
            family: string;
            /** @description 字型 id（sha256:index） */
            id: string;
            /**
             * Format: double
             * @description libass 畫這個字型時的縮放（網頁預覽的字級 = 字幕字級 × scale，大小才和燒出來的一樣）；讀不到時為 0
             */
            scale: number;
            /** @description 字型檔（@font-face 用） */
            url: string;
        };
        Guess: {
            artist: string;
            source: string;
            title: string;
        };
        Hardware: {
            gpu?: string;
            nvenc: boolean;
            /** Format: int64 */
            vram_mb?: number;
        };
        Info: {
            approval_history?: components["schemas"]["Approval"][];
            approved: components["schemas"]["Approval"];
            artist: string;
            language: string;
            link: string;
            note: string;
            targets: string[];
            title: string;
            translation: boolean;
        };
        InfoUpdate: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/v1/schemas/InfoUpdate.json
             */
            readonly $schema?: string;
            artist?: string;
            language?: string;
            link?: string;
            note?: string;
            targets?: string[];
            title?: string;
            translation?: boolean;
        };
        JobRequest: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/v1/schemas/JobRequest.json
             */
            readonly $schema?: string;
            /** @description 全部重做（含覆蓋手改的字幕） */
            force?: boolean;
            /** @description 使用者在畫面上等結果（AI 優先處理）；AI 重對一律是 */
            interactive?: boolean;
            /**
             * Format: int64
             * @description retime：第幾句（從 0 起算）
             */
            line?: number;
            /**
             * @description retime：from = 這句及之後全部、line = 只重對這句
             * @enum {string}
             */
            mode?: "from" | "line" | "";
            /** @description 批次：只做還沒做完的（已完成、缺歌詞、處理中的略過） */
            only_needed?: boolean;
            /** @description 重新對時 */
            realign?: boolean;
            /** @description 歌曲 id；好幾首時每首一件工作 */
            songs: string[];
            /** @description 步驟：separate、karaoke、check、retime */
            steps: string[];
        };
        JobResult: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/v1/schemas/JobResult.json
             */
            readonly $schema?: string;
            created: components["schemas"]["Summary"][];
            errors?: string[];
            /** @description 略過的原因 → 首數 */
            skipped: {
                [key: string]: number;
            };
        };
        LibraryOut: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/v1/schemas/LibraryOut.json
             */
            readonly $schema?: string;
            folders: components["schemas"]["FolderView"][];
            jobs: components["schemas"]["Summary"][];
            settings: components["schemas"]["Settings"];
            songs: components["schemas"]["SongView"][];
            workers: components["schemas"]["Worker"][];
        };
        Line: {
            kind: string;
            rubies: components["schemas"]["Ruby"][];
            singer: string | null;
            text: string;
            translation: string;
        };
        LineEdit: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/v1/schemas/LineEdit.json
             */
            readonly $schema?: string;
            /** @description 演唱者：男、女、合；空字串 = 不標 */
            singer?: string;
            /** @description 新的歌詞文字（改了之後要重新對時） */
            text?: string;
        };
        LogOut: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/v1/schemas/LogOut.json
             */
            readonly $schema?: string;
            job: components["schemas"]["Summary"];
            lines: string[];
            /**
             * Format: int64
             * @description 下次從這一行開始取
             */
            next: number;
        };
        LyricsMeta: {
            artist: string;
            title: string;
        };
        LyricsPutBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/v1/schemas/LyricsPutBody.json
             */
            readonly $schema?: string;
            /** @description 存檔格式的歌詞；空字串 = 刪除歌詞 */
            text: string;
        };
        LyricsViews: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/v1/schemas/LyricsViews.json
             */
            readonly $schema?: string;
            annotated: string;
            doc: components["schemas"]["EditorDoc"];
            /** @description 已經有歌詞檔 */
            exists: boolean;
            paren: string[];
            pending_readings?: number[];
            plain: string;
            text: string;
        };
        MediaView: {
            hint: string;
            /** @enum {string} */
            kind: "karaoke" | "karaoke_original" | "instrumental" | "vocals" | "source";
            label: string;
            url: string;
        };
        PlaceRequest: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/v1/schemas/PlaceRequest.json
             */
            readonly $schema?: string;
            /** @description 排在這個項目前面；空字串 = 排到最後 */
            before?: string;
            /** @description 要移動的項目；好幾首歌時依這個順序放，彼此的先後保留 */
            ids: string[];
            keep_present?: boolean;
            /**
             * @description 拖曳的是資料夾還是歌
             * @enum {string}
             */
            kind: "folder" | "song";
            /** @description 放進哪個資料夾（空字串 = 最上層） */
            parent: string;
        };
        QACounts: {
            /** Format: int64 */
            suspect: number;
            /** Format: int64 */
            wrong: number;
        };
        QALine: {
            /** Format: double */
            end: number;
            /** Format: int64 */
            index: number;
            /** Format: double */
            match: number;
            /** Format: double */
            offset: number | null;
            reasons: string[];
            /** Format: double */
            start: number;
            status: string;
            text: string;
        };
        QAView: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/v1/schemas/QAView.json
             */
            readonly $schema?: string;
            /** @description 檢查過，而且對時之後沒改過 */
            checked: boolean;
            checked_at?: string;
            lines: components["schemas"]["QALine"][];
        };
        Result: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/v1/schemas/Result.json
             */
            readonly $schema?: string;
            /** @description 新放的（含更新） */
            added: string[];
            /** @description 原曲音訊做不出來的歌（例如來源沒有音軌），這次只匯出伴唱帶 */
            failed: string[];
            /**
             * Format: int64
             * @description 已經是最新、沒有動的
             */
            kept: number;
            /** @description 放置方式：clone / link / copy */
            method?: string;
            /** @description 拿掉的（取消確認、改名、換資料夾） */
            removed: string[];
            /** @description 目的地已經有不是這個程式放的同名檔，沒有覆蓋 */
            skipped: string[];
        };
        Ruby: {
            /** Format: int64 */
            end: number;
            reading: string;
            /** Format: int64 */
            start: number;
        };
        Segment: {
            /** Format: int64 */
            end: number;
            manual: boolean;
            ruby: string | null;
            slot?: boolean;
            /** Format: int64 */
            start: number;
            text: string;
        };
        Settings: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/v1/schemas/Settings.json
             */
            readonly $schema?: string;
            /** @description 匯出時也匯出原曲音訊（有人聲，m4a，檔名加 _original） */
            export_original: boolean;
            fonts: {
                [key: string]: string;
            };
            /** Format: double */
            subtitle_scale: number;
        };
        SettingsUpdate: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/v1/schemas/SettingsUpdate.json
             */
            readonly $schema?: string;
            /** @description 匯出時也匯出原曲音訊（m4a，檔名加 _original） */
            export_original?: boolean;
            /** @description 語言 → 字型 id；null = 改回預設字型 */
            fonts?: {
                [key: string]: string | null;
            };
            /**
             * Format: double
             * @description 字幕大小（1 = 預設）
             */
            subtitle_scale?: number;
        };
        ShiftRequest: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/v1/schemas/ShiftRequest.json
             */
            readonly $schema?: string;
            /**
             * Format: double
             * @description 移動量（秒）；正數往後、負數往前
             */
            delta?: number;
            /** @description 之後的句子一起移（UI 只移單句；整段偏掉交給 AI 重對） */
            following?: boolean;
            /**
             * Format: double
             * @description 新的開始時間（秒）；和 delta 擇一
             */
            start?: number;
        };
        SongView: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/v1/schemas/SongView.json
             */
            readonly $schema?: string;
            /** @description 改了歌詞、只需重對改到的句子時（其他句子的時間含手動調整都不動）：要重對幾句、拿掉幾句；整首重新對時或不需要對時時為 null */
            align_patch: components["schemas"]["AlignPatch"];
            approval: components["schemas"]["ApprovalView"];
            /** @description 實際使用的演唱者 */
            artist: string;
            /** @description 在匯出資料夾裡的相對路徑（不論伴唱帶做好了沒） */
            export: string;
            /**
             * @description exported = 已匯出最新的成品；pending = 已確認但還沒匯出（或成品更新了、改了名、原曲音訊的設定改了）；remove = 取消確認了，下次匯出會從匯出資料夾拿掉；空字串 = 沒確認，不匯出
             * @enum {string}
             */
            exported: "exported" | "pending" | "remove" | "";
            /** @description 所在資料夾 id；最上層為空字串 */
            folder: string;
            /** @description 成品用的字型（播放畫面的即時字幕用同一個字型預覽）；找不到字型時為 null */
            font: components["schemas"]["FontView"];
            /** @description 自動辨識的歌名與演唱者（資訊對話框的提示） */
            guess: components["schemas"]["Guess"];
            /** @description 歌曲 id：YouTube 影片 id、其他網站「網站-影片 id」、手動放入 local-xxxxxxxx */
            id: string;
            /** @description 使用者設定的歌曲資訊（空字串 = 自動） */
            info: components["schemas"]["Info"];
            /** @description 還沒結束的工作（沒有時為 null） */
            job: components["schemas"]["Summary"];
            /** @description 實際的演唱語言（手動指定 > 依歌詞文字判斷）；判斷不出來時為空 */
            language: string;
            /** @description 歌詞檔的 # title / # artist（資訊對話框提示留空時用什麼） */
            lyrics_meta: components["schemas"]["LyricsMeta"];
            /** @description 可以播放的版本，第一個是預設（最終成品優先） */
            media: components["schemas"]["MediaView"][];
            /**
             * Format: int64
             * @description 同一層內的順序
             */
            order: number;
            /** @description 這首歌的資料夾（NAS 上的路徑，可以複製） */
            path: string;
            source: components["schemas"]["SourceView"];
            status: components["schemas"]["Status"];
            /** @description 實際使用的歌名（手動 > 歌詞檔的 # title > 自動辨識） */
            title: string;
            /**
             * Format: int64
             * @description 歌詞裡有翻譯的句數
             */
            translation_lines: number;
        };
        SourceView: {
            added_at: string;
            channel?: string;
            /** Format: double */
            duration: number;
            /** Format: int64 */
            height?: number;
            /** @enum {string} */
            kind: "url" | "local";
            /** @enum {string} */
            mode: "video" | "audio";
            /** @description 影片原始標題（手動放入時是檔名） */
            title: string;
            url?: string;
            /** Format: int64 */
            width?: number;
        };
        Status: {
            approval: string;
            download: string;
            karaoke: string;
            lyrics: string;
            qa: components["schemas"]["QACounts"];
            separate: string;
        };
        Summary: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/v1/schemas/Summary.json
             */
            readonly $schema?: string;
            cancelling: boolean;
            /** Format: date-time */
            created: string;
            error?: string;
            /** Format: date-time */
            finished?: string;
            force: boolean;
            id: string;
            lane: string;
            /** Format: int64 */
            log_size: number;
            priority: string;
            /** Format: double */
            progress: number | null;
            realign: boolean;
            song: string;
            stage: string;
            /** Format: date-time */
            started?: string;
            status: string;
            steps: string[];
            title: string;
            url?: string;
        };
        System: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/v1/schemas/System.json
             */
            readonly $schema?: string;
            /** @description 資料備份的路徑 */
            data: string;
            /** @description 曲庫所在硬碟的用量 */
            disk: components["schemas"]["Disk"];
            /** @description 曲庫的路徑 */
            library: string;
            /** Format: int64 */
            songs: number;
            started_at: string;
            /** @description 演算法 / 協定版本（versions.json） */
            versions: components["schemas"]["Versions"];
            workers: components["schemas"]["Worker"][];
            /** @description yt-dlp 的版本 */
            ytdlp: string;
            /** @description 可以退回的上一版 */
            ytdlp_prev?: string;
        };
        TimingLine: {
            /** Format: double */
            end: number;
            /** Format: int64 */
            index: number;
            /** Format: double */
            start: number;
            text: string;
            words: components["schemas"]["Word"][];
        };
        TimingView: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/v1/schemas/TimingView.json
             */
            readonly $schema?: string;
            adjustments: components["schemas"]["Adjustment"][];
            /** @description 還沒對時時為空 */
            lines: components["schemas"]["TimingLine"][];
            /** @description 這次一起被推動的句子（從 0 起算） */
            pushed?: number[];
        };
        Versions: {
            /** Format: int64 */
            align: number;
            /** Format: int64 */
            protocol: number;
            /** Format: int64 */
            qa: number;
            /** Format: int64 */
            reading: number;
            /** Format: int64 */
            render: number;
            /** Format: int64 */
            separate: number;
        };
        Views: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/v1/schemas/Views.json
             */
            readonly $schema?: string;
            annotated: string;
            doc: components["schemas"]["EditorDoc"];
            paren: string[];
            pending_readings?: number[];
            plain: string;
            text: string;
        };
        Word: {
            /** Format: double */
            end: number;
            /** Format: double */
            start: number;
            text: string;
        };
        Worker: {
            channels: string[];
            disabled: boolean;
            hardware: components["schemas"]["Hardware"];
            kinds: string[];
            /** Format: date-time */
            last_seen: string;
            name: string;
            online: boolean;
            tasks: components["schemas"]["WorkerTask"][];
            version_diff?: string[];
            version_ok: boolean;
            versions: components["schemas"]["Versions"];
        };
        WorkerPatchBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/v1/schemas/WorkerPatchBody.json
             */
            readonly $schema?: string;
            /** @description true = 停用（領不到新任務） */
            disabled: boolean;
        };
        WorkerTask: {
            id: string;
            kind: string;
            song: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    export: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Result"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-folders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FolderView"][];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "add-folder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FolderInBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FolderView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "delete-folder": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 資料夾 id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "update-folder": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 資料夾 id */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FolderPatchBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FolderView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-fonts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Font"][];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Summary"][];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "submit-jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobRequest"];
            };
        };
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResult"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-job": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 工作 id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Summary"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "cancel-job": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 工作 id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Summary"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-job-log": {
        parameters: {
            query?: {
                /** @description 從第幾行開始（上次回應的 next） */
                offset?: number;
            };
            header?: never;
            path: {
                /** @description 工作 id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogOut"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-library": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryOut"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    place: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlaceRequest"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "convert-lyrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConvertRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Views"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Settings"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "update-settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsUpdate"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Settings"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-songs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SongView"][];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "add-song": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddRequest"];
            };
        };
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Summary"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-song": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 歌曲 id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SongView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "update-song": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 歌曲 id */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InfoUpdate"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SongView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "set-approval": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 歌曲 id */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApprovalInBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SongView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "edit-line": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 歌曲 id */
                id: string;
                /** @description 第幾句（要唱的句子，從 0 起算） */
                n: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LineEdit"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LyricsViews"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-lyrics": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 歌曲 id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LyricsViews"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "put-lyrics": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 歌曲 id */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LyricsPutBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LyricsViews"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-qa": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 歌曲 id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QAView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-timing": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 歌曲 id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimingView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "shift-line": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 歌曲 id */
                id: string;
                /** @description 第幾句（從 0 起算，與對時結果一致） */
                n: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ShiftRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimingView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-system": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["System"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "rollback-ytdlp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["System"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-workers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Worker"][];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "update-worker": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description AI 伺服器名稱 */
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkerPatchBody"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
}
